### ISSUE TITLE
Cuestionario previo

### ISSUE THREAD

**Issue by AnthonyAS15** [AnthonyAS15/Intro-a-HDLs-y-herramientas-EDA#1]
Fecha de entrega: 15 / 02 / 2024

Se responde en un proyecto compartido en Overleaf.

**Comment by Siuuuuuuu07** [comment]
El cuestionario previo de este laboratorio, por ende, al ser 3 estudiantes el trabajo se distribuirá con 5 preguntas por estudiante

**Comment by PriscillaCamposZamora** [comment]
Proyecto en Overleaf (solo ver): https://www.overleaf.com/read/pygdgkptpmbb#8d6761

**Comment by PriscillaCamposZamora** [comment]
Hoy se aclararon dudas sobre preguntas 5 y 9 en sesión sincrónica de Zoom.

**Comment by PriscillaCamposZamora** [comment]
Preguntas 5, 6, 9, 11, 12 terminada
[cuestionario_lab_1_taller_diseño_digital_avance.pdf](https://github.com/AnthonyAS15/Intro-a-HDLs-y-herramientas-EDA/files/14274012/cuestionario_lab_1_taller_diseno_digital_avance.pdf)
s.

**Comment by AnthonyAS15** [comment]
El resto de las preguntas terminadas.
