### ISSUE TITLE
Realizar la documentación

### ISSUE THREAD

**Issue by AnthonyAS15** [AnthonyAS15/Intro-a-HDLs-y-herramientas-EDA#8]
Se realizará en un documento en Overleaf.

Cada miembro añadirá a la documentación los problemas que tuvieron a lo largo del trabajo y la manera en que solucionaron dichos problemas.

**Comment by PriscillaCamposZamora** [comment]
**Distribución de documentación:**

- Documentar ejercicio 1: @Siuuuuuuu07 

- Documentar ejercicio 2: @PriscillaCamposZamora 

- Documentar ejercicio 3: @AnthonyAS15 

- Documentar ejercicio 4: @PriscillaCamposZamora 

- Documentar ejercicio 5: @PriscillaCamposZamora 

- Documentar ejercicio 6: @AnthonyAS15

**Comment by PriscillaCamposZamora** [comment]
Enlace a documento compartido en Overleaf para trabajar en la documentación: [link](https://www.overleaf.com/read/fhbzfwgcwtjg#21185d)

**Comment by PriscillaCamposZamora** [comment]
No funciona en la FPGA:(

Los segmentos encienden con cero: 🤦‍♀️🤦‍♀️

**Comment by PriscillaCamposZamora** [comment]
Prueba fallida:

https://github.com/AnthonyAS15/Intro-a-HDLs-y-herramientas-EDA/assets/139295658/a19f752c-2cc6-4e3b-ad80-8620ab6be711
